In [53]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


# Load libraries
#import pandas
#from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [54]:
data = pd.read_csv(r"D:\projects\ILEquandl\ILE_EVENTS.csv")

In [55]:
data.describe()

gsubind    ind_score    prob_good       impact  enacted  \
count  3.045000e+03  3045.000000  3045.000000  3045.000000   3045.0   
mean   2.822167e+07     0.328262     0.351635     0.146321      1.0   
std    1.079148e+07     0.085496     0.243571     0.241632      0.0   
min    1.010101e+07     0.250067    -0.936869     0.001000      1.0   
25%    2.020201e+07     0.273668     0.172178     0.019518      1.0   
50%    2.530201e+07     0.302867     0.372695     0.042091      1.0   
75%    4.010101e+07     0.347325     0.532898     0.096119      1.0   
max    6.010202e+07     0.797741     0.940006     0.999812      1.0   

       introduced  passed_first_chamber  passed_second_chamber   resolution  
count      3045.0                3045.0                 3045.0  3045.000000  
mean          0.0                   0.0                    0.0     0.776355  
std           0.0                   0.0                    0.0     0.416755  
min           0.0                   0.0                    0.0     0.000000  
25%           0.0                   0.0                    0.0     1.000000  
50%           0.0                   0.0                    0.0     1.000000  
75%           0.0                   0.0                    0.0     1.000000  
max           0.0                   0.0                    0.0     1.000000

In [56]:
data.head()

event_date             natural_id   gsubind  ind_score  prob_good  \
0    3/7/2008  us_20072008r_SRES 476  10101010   0.266664   0.625386   
1   5/19/2005  us_20052006r_SRES 151  10101010   0.280333   0.694916   
2   4/26/2007  us_20072008r_SRES 175  10101010   0.271362   0.709141   
3    6/2/2009  us_20092010r_SRES 139  10101010   0.270501   0.588757   
4  11/18/2011  us_20112012r_HRES 470  10101010   0.254308   0.614090   

     impact  enacted  introduced  passed_first_chamber  passed_second_chamber  \
0  0.001542        1           0                     0                      0   
1  0.006062        1           0                     0                      0   
2  0.006605        1           0                     0                      0   
3  0.007583        1           0                     0                      0   
4  0.008273        1           0                     0                      0   

   resolution  
0           1  
1           1  
2           1  
3           1  
4           1

In [57]:
data1 = data[["gsubind", "prob_good", "impact"]]

In [58]:
data1.head()

gsubind  prob_good    impact
0  10101010   0.625386  0.001542
1  10101010   0.694916  0.006062
2  10101010   0.709141  0.006605
3  10101010   0.588757  0.007583
4  10101010   0.614090  0.008273

In [59]:
#data1 = data[["PassengerId", "Pclass", "Age", "SibSp", "Parch", "Fare"]]
resultData = data.gsubind

resultData.head()

0    10101010
1    10101010
2    10101010
3    10101010
4    10101010
Name: gsubind, dtype: int64

In [60]:
resultData.head(30)

0     10101010
1     10101010
2     10101010
3     10101010
4     10101010
5     10101010
6     10101010
7     10101010
8     10101010
9     10101010
10    10101010
11    10101010
12    10101010
13    10101010
14    10101010
15    10101010
16    10101010
17    10101010
18    10101010
19    10101010
20    10101010
21    10101010
22    10101010
23    10101010
24    10101010
25    10101010
26    10101010
27    10101010
28    10101010
29    10101010
Name: gsubind, dtype: int64

In [61]:
trainData, testData, targetData, testTargetData = train_test_split(data1, resultData, test_size = 0.3, shuffle = True)

In [62]:
print(targetData.head)

<bound method NDFrame.head of 12      10101010
2233    45101010
810     20202020
1545    25302010
2311    45101010
1965    15104050
309     20202010
2042    15104050
1895    15104050
2612    45101010
2966    40101010
2504    45101010
24      10101010
234     20202010
2499    45101010
2052    30301010
1230    25301020
1138    25301020
2893    40101010
391     20202010
2699    40101010
507     20202010
427     20202010
2641    45101010
2260    45101010
1308    25301020
472     20202010
244     20202010
1746    25302010
1747    25302010
          ...   
2787    40101010
2736    40101010
2155    35103010
2672    40101010
1630    25302010
2338    45101010
2348    45101010
2275    45101010
1664    25302010
1841    25302010
171     20202010
230     20202010
181     20202010
222     20202010
2593    45101010
1532    25302010
2769    40101010
1924    15104050
1003    20202020
917     20202020
2452    45101010
2178    35103010
2064    35103010
1643    25302010
2204    45101010
2947    40101010
1

In [63]:
model = LogisticRegression()
fitModel = model.fit(trainData,targetData)
predict = fitModel.predict(testData)
confusion_matrix(testTargetData,predict)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  10,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  58,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 165,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 143,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  63,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 142,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  42,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 117,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 158,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  14,   0]], dtype=int64)

In [64]:

# Test options and evaluation metric
seed = 7
scoring = 'accuracy'
# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('RF', RandomForestClassifier()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
models.append(('MLP', MLPClassifier()))

# evaluate each model in turn
results = []
names = []


for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, trainData, targetData, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

LR: 0.146872 (0.018117)
LDA: 0.370249 (0.016859)


C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:442: UserWarning: The priors do not sum to 1. Renormalizing
  UserWarning)
C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\Madhav\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
C:\Users\Madhav\Anaconda3\li

RF: 0.971842 (0.012066)
KNN: 1.000000 (0.000000)
CART: 1.000000 (0.000000)
NB: 0.826831 (0.065297)
SVM: 1.000000 (0.000000)
MLP: 0.144531 (0.065210)


In [65]:
LR = DecisionTreeClassifier()
LR.fit(trainData, targetData)
predictions = LR.predict(testData)
print(accuracy_score(testTargetData, predictions))
print(confusion_matrix(testTargetData, predictions))
print(classification_report(testTargetData, predictions))

1.0
[[ 10   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0   0]
 [  0   0  58   0   0   0   0   0   0   0   0   0]
 [  0   0   0 165   0   0   0   0   0   0   0   0]
 [  0   0   0   0 143   0   0   0   0   0   0   0]
 [  0   0   0   0   0  63   0   0   0   0   0   0]
 [  0   0   0   0   0   0 142   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0  42   0   0   0]
 [  0   0   0   0   0   0   0   0   0 117   0   0]
 [  0   0   0   0   0   0   0   0   0   0 158   0]
 [  0   0   0   0   0   0   0   0   0   0   0  14]]
             precision    recall  f1-score   support

   10101010       1.00      1.00      1.00        10
   10102050       1.00      1.00      1.00         1
   15104050       1.00      1.00      1.00        58
   20202010       1.00      1.00      1.00       165
   20202020       1.00      1.00      1.00       143
   25301020       1.00      1.00      1.00        63
   25302010